#!/bin/bash
# fixfs: fixing file systems' name and mode
# REV09: Sat 16 Sep 2023 09:00
# REV08: Thu 30 Apr 2020 09:00
# REV07: Mon 02 Dec 2019 17:00
# REV06: Mon 24 Sep 2018 16:00
# REV05: Fri 08 Sep 2017 20:00
# START: Thu 19 Dec 2013 00:00

# Copyright (C) 2016-2023 BinKadal, Sdn.Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# Add escape \"
# Replacing all funny and white characters with a dash (-).
# Replacing multiple dashes (---) with a single dash (-)
# No dash before a dot.

function recursive() {
   ls -1 | mawk '{
      FNAME1=$0
      gsub (/\"/,"\\\"",FNAME1) 
      FNAME2=FNAME1
      NCHG=0
      NCHG += gsub (/[;:!() ^@&,\[\]\?\*\#\"\\'\'']/,"-",FNAME2) 
      NCHG += gsub (/\.-/,"-",FNAME2) 
      NCHG += gsub (/--+/,"-",FNAME2) 
      NCHG += gsub (/_-/,"-",FNAME2) 
      NCHG += gsub (/-_/,"-",FNAME2) 
      NCHG += gsub (/-\./,".",FNAME2) 
      NCHG += gsub (/\._/,"_",FNAME2) 
      NCHG += gsub (/__+/,"_",FNAME2) 
      NCHG += gsub (/_\./,".",FNAME2) 
      NCHG += gsub (/\.\.+/,".",FNAME2) 
      NCHG += gsub (/^-/,"",FNAME2) 
      NCHG += gsub (/-$/,"",FNAME2) 

      if (NCHG > 0) {
         EXTRA=""
         TMPF=FNAME2 EXTRA
         while ((getline < TMPF) >= 0) {
            EXTRA++
            TMPF=FNAME2 "-" EXTRA
         }
         system("/bin/mv -f \""  FNAME1  "\" " TMPF)
      }
   }'

   # chmod 755 for all directories
   # chmod 644 for all files
   for II in {.??,}*
   do
      [ -d "$II" ] && [ ! -L "$II" ] && {
         chmod 755 "$II"
         cd "$II"
         # Recursive inside the DIR
         recursive
         cd ..
      }
      [ -f "$II" ] && chmod 644 "$II"
   done
}

recursive

exit

